mailcatcher:
  image: dockerizedrupal/mailcatcher:1.0.1
  hostname: mailcatcher
  ports:
    - "80:80"
    - "443:443"
    - "25:25"
  environment:
    - SERVER_NAME=localhost
    - TIMEOUT=300
    - PROTOCOLS=https,http
